In [1]:
import pandas as pd
import numpy as np

In [2]:
emp_data = pd.read_csv('Hr_comma_sep.csv.txt')

In [3]:
emp_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [6]:
emp_data.rename(columns={'sales':'department'}, inplace=True)
emp_data

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       272                   4              0     1   
3                       223                   5              0     1   
4                       159                   3              0     1   
...                     ...                 ...            ...   ...   
14994                   151                   3              0     1   
14995                   160                   3              0     1   
14996                   143                   3              0     1   
14997                   280                   4              0     1   
14998                   158                   3              0     1   

       promotion_last_5years department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales  medium  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14994                      0    support     low  
14995                      0    support     low  
14996                      0    support     low  
14997                      0    support     low  
14998                      0    support     low  

[14999 rows x 10 columns]

In [7]:
emp_data.corr()['left']

satisfaction_level      -0.388375
last_evaluation          0.006567
number_project           0.023787
average_montly_hours     0.071287
time_spend_company       0.144822
Work_accident           -0.154622
left                     1.000000
promotion_last_5years   -0.061788
Name: left, dtype: float64

#### Selecting categorical columns & integer columns

In [8]:
emp_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   department             14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [9]:
cat_emp_data = emp_data.select_dtypes('object')

In [10]:
int_emp_data = emp_data.select_dtypes('int64')

#### Preprocessing Categorical Columns

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [12]:
le = LabelEncoder()
ohe = OneHotEncoder()

In [13]:
le.fit(cat_emp_data.department)

LabelEncoder()

In [14]:
cat_emp_data['department_tf'] = le.transform(cat_emp_data.department)

<ipython-input-14-905728b22d8a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_emp_data['department_tf'] = le.transform(cat_emp_data.department)


In [15]:
cat_emp_data.head()

department  salary  department_tf
0      sales     low              7
1      sales  medium              7
2      sales  medium              7
3      sales     low              7
4      sales     low              7

In [16]:
le.classes_

array(['IT', 'RandD', 'accounting', 'hr', 'management', 'marketing',
       'product_mng', 'sales', 'support', 'technical'], dtype=object)

In [17]:
le.inverse_transform([5])

array(['marketing'], dtype=object)

In [18]:
ohe.fit(cat_emp_data[['department_tf']])

OneHotEncoder()

In [20]:
department_tf = ohe.transform(cat_emp_data[['department_tf']]).toarray()
department_tf

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [21]:
from sklearn.preprocessing import FunctionTransformer

In [22]:
def func(x):
    def mapping(d):
        if d == 'low':
            return 1
        elif d == 'medium':
            return 2
        else:
            return 3
    return x.map( mapping )
        
ft = FunctionTransformer(func, validate=False)

In [62]:
cat_emp_data['salary_tf'] = ft.transform(cat_emp_data.salary)

<ipython-input-62-96c1551ebb93>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_emp_data['salary_tf'] = ft.transform(cat_emp_data.salary)


In [63]:
cat_emp_data['salary_tf']

0        1
1        2
2        2
3        1
4        1
        ..
14994    1
14995    1
14996    1
14997    1
14998    1
Name: salary_tf, Length: 14999, dtype: int64

#### Preprocessing Number Data

In [24]:
int_emp_data.head()

number_project  average_montly_hours  time_spend_company  Work_accident  \
0               2                   157                   3              0   
1               5                   262                   6              0   
2               7                   272                   4              0   
3               5                   223                   5              0   
4               2                   159                   3              0   

   left  promotion_last_5years  
0     1                      0  
1     1                      0  
2     1                      0  
3     1                      0  
4     1                      0

In [25]:
int_emp_data.drop('left',axis=1, inplace=True)

C:\Users\CHAITRA\anaconda3\lib\site-packages\pandas\core\frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [26]:
from sklearn.preprocessing import MinMaxScaler

In [35]:
mms = MinMaxScaler()

In [36]:
mms.fit(int_emp_data)

MinMaxScaler()

In [37]:
int_tf = mms.transform(int_emp_data)

In [38]:
int_tf

array([[0.        , 0.28504673, 0.125     , 0.        , 0.        ],
       [0.6       , 0.77570093, 0.5       , 0.        , 0.        ],
       [1.        , 0.82242991, 0.25      , 0.        , 0.        ],
       ...,
       [0.        , 0.21962617, 0.125     , 0.        , 0.        ],
       [0.8       , 0.85981308, 0.25      , 0.        , 0.        ],
       [0.        , 0.28971963, 0.125     , 0.        , 0.        ]])

In [39]:
float_tf = emp_data[['satisfaction_level','last_evaluation']].values
float_tf

array([[0.38, 0.53],
       [0.8 , 0.86],
       [0.11, 0.88],
       ...,
       [0.37, 0.53],
       [0.11, 0.96],
       [0.37, 0.52]])

In [40]:
cat_emp_data['salary_tf'].values.shape

(14999,)

In [41]:
int_tf.shape

(14999, 5)

In [42]:
department_tf

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

#### Joining the data

In [59]:
salary_tf = cat_emp_data['salary_tf'].values.reshape(-1,1)
salary_tf

array([[1],
       [2],
       [2],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [61]:
feature_data = np.hstack([department_tf,int_tf,float_tf,salary_tf])
feature_data

array([[0.  , 0.  , 0.  , ..., 0.38, 0.53, 1.  ],
       [0.  , 0.  , 0.  , ..., 0.8 , 0.86, 2.  ],
       [0.  , 0.  , 0.  , ..., 0.11, 0.88, 2.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.37, 0.53, 1.  ],
       [0.  , 0.  , 0.  , ..., 0.11, 0.96, 1.  ],
       [0.  , 0.  , 0.  , ..., 0.37, 0.52, 1.  ]])

In [45]:
target_data = emp_data.left

#### Split data into two parts

In [46]:
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(feature_data,target_data)

#### Model Training

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [48]:
lr = LogisticRegression()

In [49]:
lr.fit(trainX,trainY)

LogisticRegression()

In [50]:
rf = RandomForestClassifier()

In [51]:
rf.fit(trainX,trainY)

RandomForestClassifier()

#### Model Validation

In [52]:
lr.score(testX,testY)

0.7837333333333333

In [53]:
rf.score(testX,testY)

0.9904

In [54]:
from sklearn.metrics import recall_score,precision_score, f1_score, classification_report

In [55]:
pred = rf.predict(testX)

In [56]:
precision_score(y_pred=pred, y_true=testY)

0.9896788990825688

In [57]:
f1_score(y_pred=pred, y_true=testY)

0.9795686719636775

In [58]:
print (classification_report(y_pred=pred, y_true=testY))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      2860
           1       0.99      0.97      0.98       890

    accuracy                           0.99      3750
   macro avg       0.99      0.98      0.99      3750
weighted avg       0.99      0.99      0.99      3750

